### PR TITLE
PIM-5963: clean completeness calculation query to be SQL compliant

### PR DESCRIPTION
**Pull request by jjanvier**
See https://github.com/akeneo/pim-community-dev/pull/4960

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by SamirBoulil** [comment]
GTM

**Comment by nidup** [comment]
I'd keep it but change it to : MySQL 5.7 is not officialy supported but works as experimental mode if you change the "only group by stuff" config.

**Comment by jjanvier** [comment]
@nidup done

**Comment by nidup** [comment]
thx, GTM (imho for the official support we need the related CI builds, as for PHP7)

**Pull request merged**
