### PR TITLE
Move Behat setup to be easily found

### PR DESCRIPTION
**Pull request by jmleroux**

### CODE REVIEW

**Comment by BitOne** [comment]
You're taking some risk, as there's no guarantee that our Behat will work with future versions of Selenium...

**Comment by jmleroux** [comment]
@BitOne , we use Selenium 2.45 on workers.
I can update to this version.

**Comment by BitOne** [comment]
@jmleroux : Yeap, that's ok for me.

**Comment by jmleroux** [comment]
i'll check firefox version too.

**Comment by jmleroux** [comment]
@BitOne , we just apt-get install iceweasel on CI workers. No specific version.
Do we specify a version in the doc ?

**Comment by BitOne** [comment]
I would provide the version number we use today.

**Pull request closed without merging**
