### PR TITLE
TIP-816

### PR DESCRIPTION
**Pull request by matthieudelaro**

### CODE REVIEW

**Comment by matthieudelaro** [comment]
Thanks Nicolas. I was targeting last version, with commits based on master branch (or did I miss something?)

**Comment by nidup** [comment]
last released version is 2.0 (branch 2.0), we released it in september
next version is 2.1 (branch master), we'll release it in december

i think you want fix for 1.0, you can change the destination branch to 2.0

**Comment by matthieudelaro** [comment]
It's been solved in 2.0

**Comment by matthieudelaro** [comment]
The commit about default username and password moved to https://github.com/akeneo/pim-docs/pull/717

**Pull request closed without merging**
