### PR TITLE
Display docs version in a better place

### PR DESCRIPTION
**Pull request by mickaelandrieu**
A minor but useful improvement: regarding Google analytics stats, EVERY people is looking at "latest" documentation and not at the documentation for his own version.

This may lead to many errors, and probably due to the actual version position, which is not really "visible".

<details>
<summary>Before</summary>

old_menu

old_menu_2
</details>

<details>
<summary>After</summary>

new

new2
</details>

### CODE REVIEW

**Comment by nidup** [comment]
Very good idea however there is a white blank under the selector that seems really weird + or does not work on platformsh env, missing version + switching versions fails

**Comment by mickaelandrieu** [comment]
@nidup switching versions is not supposed to work when you only build a PR that rely on only one branch :)

The blank space is intended, to make a difference between the version selector and the menu: is it too much? I'm not really good at designing things :/

**Comment by nidup** [comment]
Me neither, ping @pierallard any opinion mate?

**Comment by pierallard** [comment]
I like the idea, but please set the same margin top and bottom in the "Akeneo PIM - version : xxx" block (top is bigger than bottom now)

**Comment by mickaelandrieu** [comment]
@pierallard fair enough, I've improved it (take a look to platform.sh link please)

**Comment by a2xchip** [comment]
@mickaelandrieu looks like `border-bottom-width: 1px;` for `rst-versions custom-version` class should be enough, but because it is not `<hr>` but border we need to add +1px padding top for `rst-current-version` to balance vertical alignment

**Comment by mickaelandrieu** [comment]
@a2xchip feel free to add a commit, I'm not sure to understand what you mean ^^ (and the stylesheet for the original theme is ugly as hell :(, be careful of side effects )

**Comment by a2xchip** [comment]
to look like this @mickaelandrieu 

image

**Comment by mickaelandrieu** [comment]
@a2xchip done :)

**Comment by LaureBro** [comment]
Nice idea, but don't you think it can be misleading to have this change from 1.5 version and not for versions below? For 1.2, 1.3 and 1.4 the menu will be placed at the bottom and from 1.5, it's placed on the top.. 
I think we should change it from 1st versions, even if their pages are not visited a lot.

**Comment by pierallard** [comment]
span.fa.fa-book {
    float: none;
    line-height: normal;
}

Add this code to align elements plz

**Comment by pierallard** [comment]
And I don't see Styleguides in the platform.sh, hope it's normal.

**Comment by mickaelandrieu** [comment]
@pierallard it is normal as Style guide is not generated using Sphinx and not really contributable :/

**Comment by mickaelandrieu** [comment]
@LaureBro agree :)

**Pull request merged**
