### PR TITLE
Format README headers

### PR DESCRIPTION
**Pull request by pierallard**
Change `+++` `===` and `---` to `###` to get correct headers

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers

### CODE REVIEW

**Comment by phaseinducer** [comment]
Maybe it would be a good idea to do the same with h1 and h2 ?

**Comment by pierallard** [comment]
@phaseinducer Seems good idea to me, but I don't know what is Akeneo standard for headers.

**Comment by phaseinducer** [comment]
GTM

**Comment by jjanvier** [comment]
gtm

**Pull request merged**
