### PR TITLE
Add CSV format doc for attributes

### PR DESCRIPTION
**Pull request by fitn**

### CODE REVIEW

**Comment by a2xchip** [comment]
Attribute import/export properties were changed last week by [this commit](Pim\Bundle\CatalogBundle\AttributeType\ImageType)

**Comment by jmleroux** [comment]
@a2xchip ,
could you edit your link please ? It goes to /dev/null ;)
JM

**Comment by a2xchip** [comment]
@jmleroux Five updates per minute ))))

**Comment by jmleroux** [comment]
@a2xchip ,
we actually try to document the import/export structure for 1.5 branch.
The modifications you're talking about are merged in master branch (1.6).

**Comment by a2xchip** [comment]
@jmleroux True, these links a published related to 1.6 milestone.

**Comment by jmleroux** [comment]
Anyway, thx for your help on Akeneo @a2xchip :+1:

**Pull request merged**
