### PR TITLE
Update sphinx dependencies, remove deprecated ones

### PR DESCRIPTION
**Pull request by damien-carcel**

### CODE REVIEW

**Comment by BitOne** [comment]
I think you can remove it completely, as we don't use it in your doc (this lib is used to display mathematical formulas)

**Comment by damien-carcel** [comment]
In this case, even simpler :)

**Comment by BitOne** [comment]
You can check if we use any `:math:` tag in our documentation. And anyway, removing it and checking if there's no error would tell you that (but be sure to do that on all branches).

**Comment by damien-carcel** [comment]
Checked, never used!

**Pull request merged**
