### PR TITLE
Added the information on how to add tabs to the jobs form

### PR DESCRIPTION
**Pull request by gplanchat**

### CODE REVIEW

**Comment by nidup** [comment]
Hi @gplanchat 

@phaseinducer just re-worked the cookbook related to building custom UI for a job https://docs.akeneo.com/1.7/cookbook/import_export/create-connector.html#configure-the-ui-for-our-new-job

So, imho, the change you propose here could be disturbing for a new comer, i would prefer encourage reader to use the updated cookbook.

**Comment by gplanchat** [comment]
@phaseinducer's cookbook doesn't explain how to build new tabs, such as :

image

And the other doc I changed in #564, which was entitled "How to Add a New Tab to Akeneo entities forms (except product edit form)" is not suitable for jobs.

**Comment by nidup** [comment]
Ok, i closed the PR a bit quickly, re-opening for discussion :wink: 

@phaseinducer your opinion?

**Comment by gplanchat** [comment]
Maybe some parts of the docs from the product edit for could be copied and transformed specifically for the jobs form ?

**Comment by mickaelandrieu** [comment]
ping @phaseinducer I'd like to merge it today, do you have any comment to do?

**Comment by mickaelandrieu** [comment]
@phaseinducer don't hesitate to complete/update @gplanchat 's work if needed.

Merged. Thanks for your contribution @gplanchat!

**Pull request merged**
