### PR TITLE
Fix selenium version typo

### PR DESCRIPTION
**Pull request by a2xchip**
Simple version num typo fix

### CODE REVIEW

**Comment by nidup** [comment]
locally i use selenium-server-standalone-2.53.0.jar

**Comment by pierallard** [comment]
And me 2.47.0 :trollface:

**Comment by a2xchip** [comment]
:) :D On my thinkpad i use selenium 3.x but it is not compatible with linked firefox version :eyes:

**Comment by mickaelandrieu** [comment]
Version 2.43.1 is the only valid answer => https://github.com/a2xchip/pim-docs/blob/145b10352ed5ad2f0b54c17e5e527ba4887e64a4/reference/best_practices/core/behat.rst#install-selenium-server

:trollface:

**Comment by a2xchip** [comment]
:trollface: may be this version is better?

**Comment by a2xchip** [comment]
do we have some tool that extracts links from documentation and checks for 404?

**Comment by mickaelandrieu** [comment]
@a2xchip no we dont have, GTM => thanks!

**Comment by a2xchip** [comment]
:tada:

**Pull request merged**
