### PR TITLE
TIP-298: bump Doctrine MongoDB ODM bundle

### PR DESCRIPTION
**Pull request by jjanvier**
See https://github.com/akeneo/pim-community-dev/pull/4741

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by pierallard** [comment]
GTM

**Comment by nidup** [comment]
GTM if related PR is merged

**Comment by nidup** [comment]
@jjanvier think about bump the EE too

**Comment by ClementGautier** [comment]
GTM

**Pull request merged**
