### PR TITLE
Remove doc about customization

### PR DESCRIPTION
**Pull request by jmleroux**
This documentation is not up to date and not really maintained

### CODE REVIEW

**Review by ahocquard — APPROVED** [review]
If the doc is wrong, it's more painful to follow it that not having anything.  :+1:  to remove it. But you should have approval from @BitOne at least I think.

**Comment by a-ast** [comment]
As a developer, I know that these docs are outdated and often confusing.
But those are the only source of information for extending Akeneo UI. These pages might be very useful especially by working with old PIM versions. 
Would you consider a possibility to not to remove this documentation but moving it to a special section, something like documentation about old versions, please?

**Comment by BitOne** [comment]
Hello @a-ast 

This documentation will still be available in the docs.akeneo.com on the older versions of Akeneo PIM.

**Comment by gplanchat** [comment]
Too bad those docs aren't updated, it was painful to build things before it appeared. We are going backwards.

**Review by BitOne — APPROVED** [review]

**Pull request merged**
