### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by coudenysj**

### CODE REVIEW

**Comment by nidup** [comment]
Thank you for the PR!

**Comment by nidup** [comment]
By the way, don't hesitate to claim this badge http://badger.akeneo.com/badge/0a25c62e-1bae-11e6-92dc-d60437e930cf

Have a very good day :tada:

**Comment by coudenysj** [comment]
Computer says no

**Comment by nidup** [comment]
Hi @coudenysj 

Thank you very much for raising this issue! :sweat_smile: 

We identified, fixed, tested and re-deployed with @grena (btw thx mate!).

It should be ok now, could you give a quick try please? :crossed_fingers:

Thank you!

**Pull request merged**
