### PR TITLE
Missing quote in the install command

### PR DESCRIPTION
**Pull request by gadiel**
There's a missing quote in line 15 for executing the composer command

**Description**

**Definition Of Done**

| Q                                 | A
| --------------------------------- | ---
| Technical Review and 2 GTM        | Todo
| English Review and 1 GTM          | Todo

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by jmleroux** [comment]
check contrib

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
Hello @gadiel ,

Before being able to merge this PR, would you please read and sign the following contributor agreement https://www.akeneo.com/contributor-license-agreement/ ?

**Comment by gadiel** [comment]
Hello @jmleroux,

Done!

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
Thanks a lot @gadiel ,

We will have to rebase this PR on 4.0 branch because it is the default branch to fix the current PIM documentation. Master is only for dev branch and we don't deploy it.

Would you have the time to rebase it. I can also do it for you and keep your commit.

_I am in the process of improving our contribution workflow and I made this PR to avoid this kind of mistake in the future_ :  #1443

**Pull request closed without merging**
