### PR TITLE
Introduced PIM_VERSION env var to change the version

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hello,

this is part of https://github.com/akeneo/pim-docs/issues/568.

The global idea is to not have to sed a configuration file in order to publish our documentation.

Using `PIM_VERSION` environment variable, we can change the version displayed of each Sphinx build. A default value is provided and this allow us to display the branch name instead of "master" in every build done by platform.sh for each contribution. 

> How to use/test it?

```bash
PIM_VERSION=akeneo is awesome
sphinx-build -b html . ./build
```

This contribution needs to be applied from 1.0 to master branches.

### CODE REVIEW

**Comment by juliensnz** [comment]
The default value should not be 1.0

**Comment by mickaelandrieu** [comment]
@juliensnz the pull request is for ``1.0`` and we'll not be cherry picked "as it". This is an intended choice.

**Comment by mickaelandrieu** [comment]
Thank you for reviews @fitn and @juliensnz: I'll be really careful on setting the right version in config file for each "cherry pick" to later versions

**Comment by a2xchip** [comment]
:+1:

**Pull request merged**
